// ============================================
// Shared Constants — Error Codes
// Based on SRS §7.1 error convention
// ============================================

export const ERROR_CODES = {
  // --- Auth ---
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_ALREADY_USED: 'TOKEN_ALREADY_USED',
  TOKEN_INVALID: 'TOKEN_INVALID',

  // --- Organization ---
  ORG_KEY_DUPLICATE: 'ORG_KEY_DUPLICATE',
  MEMBER_ALREADY_EXISTS: 'MEMBER_ALREADY_EXISTS',
  MEMBER_NOT_ACTIVE: 'MEMBER_NOT_ACTIVE',
  MEMBER_SUSPENDED: 'MEMBER_SUSPENDED',
  INVITATION_ALREADY_EXISTS: 'INVITATION_ALREADY_EXISTS',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  INVITATION_ALREADY_ACCEPTED: 'INVITATION_ALREADY_ACCEPTED',
  LAST_ADMIN_CANNOT_REMOVE: 'LAST_ADMIN_CANNOT_REMOVE',
  DEPARTMENT_SELF_CYCLE: 'DEPARTMENT_SELF_CYCLE',

  // --- Cross-Tenant ---
  CROSS_TENANT_REFERENCE: 'CROSS_TENANT_REFERENCE',
  CROSS_PROJECT_REFERENCE: 'CROSS_PROJECT_REFERENCE',
  TENANT_MISMATCH: 'TENANT_MISMATCH',

  // --- Project ---
  PROJECT_KEY_DUPLICATE: 'PROJECT_KEY_DUPLICATE',
  PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',
  PROJECT_NOT_READY: 'PROJECT_NOT_READY',

  // --- Workflow ---
  WORKFLOW_NO_INITIAL_STATE: 'WORKFLOW_NO_INITIAL_STATE',
  WORKFLOW_MULTIPLE_INITIAL: 'WORKFLOW_MULTIPLE_INITIAL',
  WORKFLOW_ACTIVE_VERSION_EXISTS: 'WORKFLOW_ACTIVE_VERSION_EXISTS',
  TRANSITION_NOT_FOUND: 'TRANSITION_NOT_FOUND',
  TRANSITION_GUARD_FAILED: 'TRANSITION_GUARD_FAILED',
  TRANSITION_PERMISSION_DENIED: 'TRANSITION_PERMISSION_DENIED',
  COMMENT_REQUIRED: 'COMMENT_REQUIRED',

  // --- Issue ---
  STALE_VERSION: 'STALE_VERSION',
  ISSUE_KEY_COLLISION: 'ISSUE_KEY_COLLISION',
  ISSUE_ARCHIVED: 'ISSUE_ARCHIVED',
  ISSUE_DELETED: 'ISSUE_DELETED',
  ISSUE_SELF_LINK: 'ISSUE_SELF_LINK',
  ISSUE_LINK_DUPLICATE: 'ISSUE_LINK_DUPLICATE',
  ISSUE_PARENT_CYCLE: 'ISSUE_PARENT_CYCLE',
  ISSUE_PARENT_CROSS_PROJECT: 'ISSUE_PARENT_CROSS_PROJECT',
  ISSUE_TYPE_NOT_MAPPED: 'ISSUE_TYPE_NOT_MAPPED',
  INVALID_RESOLUTION_STATE: 'INVALID_RESOLUTION_STATE',

  // --- Custom Field ---
  CUSTOM_FIELD_TYPE_MISMATCH: 'CUSTOM_FIELD_TYPE_MISMATCH',
  CUSTOM_FIELD_REQUIRED: 'CUSTOM_FIELD_REQUIRED',
  CUSTOM_FIELD_INVALID_OPTION: 'CUSTOM_FIELD_INVALID_OPTION',

  // --- Sprint ---
  SPRINT_ACTIVE_EXISTS: 'SPRINT_ACTIVE_EXISTS',
  SPRINT_NOT_SCRUM_BOARD: 'SPRINT_NOT_SCRUM_BOARD',
  SPRINT_CROSS_PROJECT: 'SPRINT_CROSS_PROJECT',

  // --- Board ---
  BOARD_RANK_COLLISION: 'BOARD_RANK_COLLISION',
  BOARD_STATE_NOT_MAPPED: 'BOARD_STATE_NOT_MAPPED',

  // --- Collaboration ---
  COMMENT_PARENT_CROSS_ISSUE: 'COMMENT_PARENT_CROSS_ISSUE',
  COMMENT_SELF_CYCLE: 'COMMENT_SELF_CYCLE',
  ATTACHMENT_COMMENT_CROSS_ISSUE: 'ATTACHMENT_COMMENT_CROSS_ISSUE',
  WORKLOG_DURATION_INVALID: 'WORKLOG_DURATION_INVALID',

  // --- Permission ---
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  SECURITY_LEVEL_DENIED: 'SECURITY_LEVEL_DENIED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // --- Catalog ---
  CATALOG_ITEM_ARCHIVED: 'CATALOG_ITEM_ARCHIVED',
  CATALOG_ITEM_REFERENCED: 'CATALOG_ITEM_REFERENCED',

  // --- General ---
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
