import { MigrationInterface, QueryRunner } from 'typeorm';

export class ProductivityAutomation1710000007000 implements MigrationInterface {
  name = 'ProductivityAutomation1710000007000';
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS dashboards (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES organizations(id), owner_member_id uuid NOT NULL REFERENCES organization_members(id), name varchar(160) NOT NULL, description text, status varchar(32) NOT NULL DEFAULT 'active', version int NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS dashboard_shares (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dashboard_id uuid NOT NULL REFERENCES dashboards(id) ON DELETE CASCADE, grantee_type varchar(32) NOT NULL, org_member_id uuid, project_id uuid, can_edit boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now())`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS dashboard_widgets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dashboard_id uuid NOT NULL REFERENCES dashboards(id) ON DELETE CASCADE, saved_filter_id uuid, widget_type varchar(64) NOT NULL, config_json jsonb NOT NULL DEFAULT '{}', position int NOT NULL DEFAULT 0, version int NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS automation_rules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES organizations(id), project_id uuid, created_by_member_id uuid NOT NULL REFERENCES organization_members(id), name varchar(160) NOT NULL, version int NOT NULL DEFAULT 1, status varchar(32) NOT NULL DEFAULT 'draft', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS automation_rule_components (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), rule_id uuid NOT NULL REFERENCES automation_rules(id) ON DELETE CASCADE, parent_component_id uuid, component_type varchar(32) NOT NULL, component_key varchar(64) NOT NULL, config_json jsonb NOT NULL DEFAULT '{}', position int NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now())`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS automation_executions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), rule_id uuid NOT NULL REFERENCES automation_rules(id) ON DELETE CASCADE, idempotency_key varchar(180) NOT NULL, status varchar(32) NOT NULL DEFAULT 'running', result_json jsonb NOT NULL DEFAULT '{}', error_message text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(rule_id,idempotency_key))`);
  }
  async down(queryRunner: QueryRunner): Promise<void> { await queryRunner.query('DROP TABLE IF EXISTS automation_executions'); await queryRunner.query('DROP TABLE IF EXISTS automation_rule_components'); await queryRunner.query('DROP TABLE IF EXISTS automation_rules'); await queryRunner.query('DROP TABLE IF EXISTS dashboard_widgets'); await queryRunner.query('DROP TABLE IF EXISTS dashboard_shares'); await queryRunner.query('DROP TABLE IF EXISTS dashboards'); }
}