import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialSchema1710000000000 implements MigrationInterface {
  name = 'InitialSchema1710000000000';

  async up(queryRunner: QueryRunner): Promise<void> {
    const statements = [
      `CREATE EXTENSION IF NOT EXISTS "pgcrypto"`,
      `CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email varchar(320) NOT NULL UNIQUE, password_hash varchar(255) NOT NULL, full_name varchar(160) NOT NULL, avatar_url text, status varchar(32) NOT NULL DEFAULT 'active', email_verified_at timestamptz, last_login_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), key varchar(32) NOT NULL UNIQUE, name varchar(160) NOT NULL, plan varchar(32) NOT NULL DEFAULT 'free', status varchar(32) NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS organization_members (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES organizations(id), user_id uuid NOT NULL REFERENCES users(id), status varchar(32) NOT NULL DEFAULT 'invited', title varchar(160), joined_at timestamptz, invited_by_member_id uuid, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(org_id,user_id))`,
      `CREATE TABLE IF NOT EXISTS org_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES organizations(id), key varchar(64) NOT NULL, name varchar(120) NOT NULL, description text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(org_id,key))`,
      `CREATE TABLE IF NOT EXISTS org_member_roles (org_member_id uuid NOT NULL REFERENCES organization_members(id), role_id uuid NOT NULL REFERENCES org_roles(id), granted_at timestamptz NOT NULL DEFAULT now(), granted_by_member_id uuid, PRIMARY KEY(org_member_id,role_id))`,
      `CREATE TABLE IF NOT EXISTS org_role_permission_entries (role_id uuid NOT NULL REFERENCES org_roles(id), permission_key varchar(100) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(role_id,permission_key))`,
      `CREATE TABLE IF NOT EXISTS auth_sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), refresh_token_hash varchar(64) NOT NULL UNIQUE, status varchar(32) NOT NULL DEFAULT 'active', ip_address varchar(64), user_agent text, expires_at timestamptz NOT NULL, last_seen_at timestamptz, revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS email_verification_tokens (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), email varchar(320) NOT NULL, token_hash varchar(64) NOT NULL UNIQUE, expires_at timestamptz NOT NULL, used_at timestamptz, created_at timestamptz NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS password_reset_tokens (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), token_hash varchar(64) NOT NULL UNIQUE, expires_at timestamptz NOT NULL, used_at timestamptz, created_at timestamptz NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS organization_invitations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES organizations(id), email varchar(320) NOT NULL, invited_by_member_id uuid NOT NULL, org_role_id uuid, token_hash varchar(64) NOT NULL UNIQUE, status varchar(32) NOT NULL DEFAULT 'pending', expires_at timestamptz NOT NULL, accepted_by_user_id uuid, accepted_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS departments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES organizations(id), name varchar(120) NOT NULL, parent_department_id uuid, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(org_id,name))`,
      `CREATE TABLE IF NOT EXISTS department_members (department_id uuid NOT NULL REFERENCES departments(id), org_member_id uuid NOT NULL REFERENCES organization_members(id), role_in_department varchar(80), joined_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(department_id,org_member_id))`,
      `CREATE TABLE IF NOT EXISTS groups (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES organizations(id), name varchar(120) NOT NULL, description text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(org_id,name))`,
      `CREATE TABLE IF NOT EXISTS group_members (group_id uuid NOT NULL REFERENCES groups(id), org_member_id uuid NOT NULL REFERENCES organization_members(id), added_at timestamptz NOT NULL DEFAULT now(), added_by_member_id uuid, PRIMARY KEY(group_id,org_member_id))`,
      `CREATE TABLE IF NOT EXISTS projects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES organizations(id), key varchar(32) NOT NULL, name varchar(160) NOT NULL, description text, visibility varchar(32) NOT NULL DEFAULT 'private', created_by_member_id uuid NOT NULL, next_issue_number bigint NOT NULL DEFAULT 1, workflow_key varchar(64), permission_scheme_id uuid, archived_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(org_id,key))`,
      `CREATE TABLE IF NOT EXISTS project_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id), key varchar(64) NOT NULL, name varchar(120) NOT NULL, description text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(project_id,key))`,
      `CREATE TABLE IF NOT EXISTS project_members (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id), org_member_id uuid NOT NULL REFERENCES organization_members(id), status varchar(32) NOT NULL DEFAULT 'active', joined_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(project_id,org_member_id))`,
      `CREATE TABLE IF NOT EXISTS project_member_roles (project_member_id uuid NOT NULL REFERENCES project_members(id), project_role_id uuid NOT NULL REFERENCES project_roles(id), granted_at timestamptz NOT NULL DEFAULT now(), granted_by_member_id uuid, PRIMARY KEY(project_member_id,project_role_id))`,
      `CREATE TABLE IF NOT EXISTS project_group_roles (group_id uuid NOT NULL REFERENCES groups(id), project_role_id uuid NOT NULL REFERENCES project_roles(id), granted_at timestamptz NOT NULL DEFAULT now(), granted_by_member_id uuid, PRIMARY KEY(group_id,project_role_id))`,
      `CREATE TABLE IF NOT EXISTS permission_schemes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id), name varchar(120) NOT NULL, description text, created_at timestamptz NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS permission_scheme_entries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), scheme_id uuid NOT NULL REFERENCES permission_schemes(id), permission_key varchar(100) NOT NULL, project_role_id uuid NOT NULL REFERENCES project_roles(id), UNIQUE(scheme_id,permission_key,project_role_id))`,
      `CREATE TABLE IF NOT EXISTS boards (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id), board_type varchar(32) NOT NULL DEFAULT 'kanban', name varchar(160) NOT NULL, description text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS board_columns (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), board_id uuid NOT NULL REFERENCES boards(id), name varchar(120) NOT NULL, position int NOT NULL, wip_limit int, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(board_id,position))`,
      `CREATE TABLE IF NOT EXISTS workflows (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES organizations(id), key varchar(64) NOT NULL, name varchar(160) NOT NULL, version int NOT NULL DEFAULT 1, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(org_id,key,version))`,
      `CREATE TABLE IF NOT EXISTS workflow_states (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workflow_id uuid NOT NULL REFERENCES workflows(id), key varchar(64) NOT NULL, name varchar(120) NOT NULL, category varchar(32) NOT NULL DEFAULT 'todo', is_initial boolean NOT NULL DEFAULT false, is_terminal boolean NOT NULL DEFAULT false, position int NOT NULL DEFAULT 0)`,
      `CREATE TABLE IF NOT EXISTS workflow_transitions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workflow_id uuid NOT NULL REFERENCES workflows(id), key varchar(64) NOT NULL, name varchar(120) NOT NULL, from_state_id uuid NOT NULL, to_state_id uuid NOT NULL, require_comment boolean NOT NULL DEFAULT false, sort_order int NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS workflow_transition_guards (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), transition_id uuid NOT NULL REFERENCES workflow_transitions(id), guard_type varchar(32) NOT NULL, config_json jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS issue_types (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES organizations(id), key varchar(64) NOT NULL, name varchar(120) NOT NULL, description text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(org_id,key))`,
      `CREATE TABLE IF NOT EXISTS custom_fields (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES organizations(id), key varchar(64) NOT NULL, name varchar(120) NOT NULL, field_type varchar(32) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(org_id,key))`,
      `CREATE TABLE IF NOT EXISTS custom_field_contexts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), custom_field_id uuid NOT NULL REFERENCES custom_fields(id), project_id uuid NOT NULL REFERENCES projects(id), issue_type_id uuid NOT NULL REFERENCES issue_types(id), is_required boolean NOT NULL DEFAULT false, position int NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(custom_field_id,project_id,issue_type_id))`,
      `CREATE TABLE IF NOT EXISTS custom_field_options (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), custom_field_id uuid NOT NULL REFERENCES custom_fields(id), value varchar(120) NOT NULL, label varchar(160) NOT NULL, position int NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS issue_custom_field_values (issue_id uuid NOT NULL REFERENCES issues(id), custom_field_context_id uuid NOT NULL REFERENCES custom_field_contexts(id), value_json jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(issue_id,custom_field_context_id))`,
      `CREATE TABLE IF NOT EXISTS issues (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES organizations(id), project_id uuid NOT NULL REFERENCES projects(id), issue_type_id uuid NOT NULL REFERENCES issue_types(id), workflow_id uuid NOT NULL REFERENCES workflows(id), state_id uuid NOT NULL REFERENCES workflow_states(id), key varchar(64) NOT NULL, summary varchar(255) NOT NULL, description text, reporter_member_id uuid NOT NULL, assignee_member_id uuid, sprint_id uuid, parent_issue_id uuid, resolution_id uuid, due_at timestamptz, original_estimate_seconds int, remaining_estimate_seconds int, time_spent_seconds int NOT NULL DEFAULT 0, version int NOT NULL DEFAULT 1, resolved_at timestamptz, archived_at timestamptz, deleted_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(project_id,key))`,
      `CREATE TABLE IF NOT EXISTS sprints (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id), board_id uuid NOT NULL REFERENCES boards(id), name varchar(160) NOT NULL, goal text, state varchar(32) NOT NULL DEFAULT 'planned', start_at timestamptz, end_at timestamptz, closed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS comments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES organizations(id), issue_id uuid NOT NULL REFERENCES issues(id), author_member_id uuid NOT NULL, parent_comment_id uuid, body text NOT NULL, body_format varchar(32) NOT NULL DEFAULT 'plain', deleted_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS work_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), issue_id uuid NOT NULL REFERENCES issues(id), author_member_id uuid NOT NULL, time_spent_seconds int NOT NULL, started_at timestamptz NOT NULL, comment text, deleted_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS issue_sprint_history (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), issue_id uuid NOT NULL REFERENCES issues(id), sprint_id uuid NOT NULL REFERENCES sprints(id), added_by_member_id uuid NOT NULL, added_at timestamptz NOT NULL DEFAULT now(), removed_by_member_id uuid, removed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS issue_state_history (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES organizations(id), issue_id uuid NOT NULL REFERENCES issues(id), from_state_id uuid NOT NULL, to_state_id uuid NOT NULL, transition_id uuid NOT NULL, actor_member_id uuid NOT NULL, comment text, idempotency_key varchar(180), version_before int NOT NULL, version_after int NOT NULL, occurred_at timestamptz NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS activity_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES organizations(id), actor_type varchar(32) NOT NULL DEFAULT 'member', actor_member_id uuid, project_id uuid, issue_id uuid, event_type varchar(120) NOT NULL, payload_json jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS outbox_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES organizations(id), aggregate_type varchar(64) NOT NULL, aggregate_id uuid NOT NULL, event_type varchar(120) NOT NULL, payload_json jsonb NOT NULL, status varchar(32) NOT NULL DEFAULT 'pending', idempotency_key varchar(180) NOT NULL, occurred_at timestamptz NOT NULL DEFAULT now(), published_at timestamptz, retry_count int NOT NULL DEFAULT 0, last_error text, UNIQUE(org_id,idempotency_key))`,
      `CREATE TABLE IF NOT EXISTS notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES organizations(id), recipient_member_id uuid NOT NULL, outbox_event_id uuid NOT NULL REFERENCES outbox_events(id), notification_type varchar(120) NOT NULL, title varchar(200) NOT NULL, body text NOT NULL, data_json jsonb NOT NULL DEFAULT '{}', sent_at timestamptz, read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(outbox_event_id,recipient_member_id,notification_type))`,
      `CREATE TABLE IF NOT EXISTS labels (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES organizations(id), name varchar(120) NOT NULL, archived_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(org_id,name))`,
      `CREATE TABLE IF NOT EXISTS issue_labels (issue_id uuid NOT NULL REFERENCES issues(id), label_id uuid NOT NULL REFERENCES labels(id), added_by_member_id uuid NOT NULL, added_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(issue_id,label_id))`,
      `CREATE TABLE IF NOT EXISTS issue_watchers (issue_id uuid NOT NULL REFERENCES issues(id), org_member_id uuid NOT NULL REFERENCES organization_members(id), added_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(issue_id,org_member_id))`,
      `CREATE TABLE IF NOT EXISTS issue_link_types (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES organizations(id), key varchar(64) NOT NULL, outward_label varchar(120) NOT NULL, inward_label varchar(120) NOT NULL, directionality varchar(32) NOT NULL DEFAULT 'directed', archived_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(org_id,key))`,
      `CREATE TABLE IF NOT EXISTS issue_links (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES organizations(id), issue_id uuid NOT NULL REFERENCES issues(id), linked_issue_id uuid NOT NULL REFERENCES issues(id), link_type_id uuid NOT NULL REFERENCES issue_link_types(id), created_by_member_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(issue_id,linked_issue_id,link_type_id))`,
      `CREATE TABLE IF NOT EXISTS board_column_states (board_column_id uuid NOT NULL REFERENCES board_columns(id), workflow_state_id uuid NOT NULL REFERENCES workflow_states(id), PRIMARY KEY(board_column_id,workflow_state_id))`,
      `CREATE TABLE IF NOT EXISTS board_issue_positions (board_id uuid NOT NULL REFERENCES boards(id), issue_id uuid NOT NULL REFERENCES issues(id), rank varchar(255) NOT NULL, updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(board_id,issue_id))`,
    ];
    for (const statement of statements) await queryRunner.query(statement);
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    const tables = ['board_issue_positions','board_column_states','issue_custom_field_values','custom_field_options','custom_field_contexts','custom_fields','issue_links','issue_link_types','issue_watchers','issue_labels','labels','notifications','outbox_events','activity_logs','issue_state_history','issue_sprint_history','work_logs','comments','sprints','issues','issue_types','workflow_transition_guards','workflow_transitions','workflow_states','workflows','board_columns','boards','permission_scheme_entries','permission_schemes','project_member_roles','project_group_roles','project_members','project_roles','projects','group_members','groups','department_members','departments','organization_invitations','password_reset_tokens','email_verification_tokens','auth_sessions','org_role_permission_entries','org_member_roles','org_roles','organization_members','organizations','users'];
    for (const table of tables) await queryRunner.query(`DROP TABLE IF EXISTS ${table} CASCADE`);
  }
}
