export function organizationManagementPanel(state, escapeHtml) {
  const activeMembers = state.members.filter((member) => member.status === 'active');
  const options = (items, label) => items.map((item) => `<option value="${item.id}">${escapeHtml(label(item))}</option>`).join('');
  const members = options(activeMembers, (member) => `${member.fullName} · ${member.email}`);
  const roles = options(state.orgRoles, (role) => role.name);
  const departments = options(state.departments, (department) => department.name);
  const groups = options(state.groups, (group) => group.name);
  return `<section class="admin-grid"><div class="panel"><div class="panel-heading"><div><p class="eyebrow">ORGANIZATION ROLES</p><h3>Access policy</h3></div></div>${state.orgRoles.map((role) => `<div class="admin-row"><span><strong>${escapeHtml(role.name)}</strong><small>${escapeHtml(role.key)}</small></span></div>`).join('') || '<div class="empty">No roles.</div>'}<form id="org-role-form" class="admin-form"><label>Role key<input name="key" required></label><label>Role name<input name="name" required></label><label>Permissions, comma-separated<input name="permissionKeys" placeholder="MANAGE_USERS"></label><button class="button ghost">Create role</button></form><form id="org-role-assignment-form" class="admin-form"><label>Member<select name="memberId" required>${members}</select></label><label>Role<select name="roleId" required>${roles}</select></label><button class="button ghost">Assign role</button></form></div><div class="panel"><div class="panel-heading"><div><p class="eyebrow">DEPARTMENTS</p><h3>Organization tree</h3></div></div>${state.departments.map((department) => `<div class="admin-row"><span><strong>${escapeHtml(department.name)}</strong><small>${department.parentDepartmentId ? 'Nested' : 'Root'}</small></span></div>`).join('') || '<div class="empty">No departments.</div>'}<form id="department-form" class="admin-form"><label>Name<input name="name" required></label><label>Parent<select name="parentDepartmentId"><option value="">None</option>${departments}</select></label><button class="button ghost">Create department</button></form><form id="department-member-form" class="admin-form"><label>Department<select name="departmentId" required>${departments}</select></label><label>Member<select name="memberId" required>${members}</select></label><button class="button ghost">Add member</button></form></div><div class="panel"><div class="panel-heading"><div><p class="eyebrow">GROUPS</p><h3>Reusable access groups</h3></div></div>${state.groups.map((group) => `<div class="admin-row"><span><strong>${escapeHtml(group.name)}</strong><small>${escapeHtml(group.description || 'No description')}</small></span></div>`).join('') || '<div class="empty">No groups.</div>'}<form id="group-form" class="admin-form"><label>Name<input name="name" required></label><label>Description<input name="description"></label><button class="button ghost">Create group</button></form><form id="group-member-form" class="admin-form"><label>Group<select name="groupId" required>${groups}</select></label><label>Member<select name="memberId" required>${members}</select></label><button class="button ghost">Add member</button></form></div></section>`;
}
